Refactor book
tkrutowski/Library pull request #6
Opened 2020-11-16 17:38 UTC by tkrutowski

- dodawanie książki gdy autor i kategorie już istnieją w bazie
- pobieranie jednej książki po ID

2020-11-16 21:38 UTC, pawel-matyaszczyk requested changes

2020-11-16 21:38 UTC, pawel-matyaszczyk commented on src/main/java/pl/sda/library/api/BookController.java
>          List<Book> getBooksFromUpolujEbooka = new ArrayList<>();
Do wyrzucenia

2020-11-16 21:38 UTC, pawel-matyaszczyk commented on src/main/java/pl/sda/library/domain/model/Book.java
> +    public boolean equals(Object o) {
Popraw nazwę obiektu

2020-11-16 21:38 UTC, pawel-matyaszczyk commented on src/main/java/pl/sda/library/infrastructure/jpa/BookRepositoryAdapter.java
> +        throw new NotYetImplementedException();
//Todo

2020-11-16 21:48 UTC, tkrutowski commented on src/main/java/pl/sda/library/domain/model/Book.java
> +    public boolean equals(Object o) {
że na Book?

2020-11-16 21:50 UTC, tkrutowski commented on src/main/java/pl/sda/library/infrastructure/jpa/BookRepositoryAdapter.java
> +        throw new NotYetImplementedException();
Tam jest w wielu miejscach mnóstwo TODO więc nie wiem czy jest sens tylko tu zaznaczać

2020-11-16 21:51 UTC, tkrutowski commented on src/main/java/pl/sda/library/api/BookController.java
>          List<Book> getBooksFromUpolujEbooka = new ArrayList<>();
wyrzucone

2020-11-16 22:09 UTC, pawel-matyaszczyk commented on src/main/java/pl/sda/library/domain/model/Book.java
> +    public boolean equals(Object o) {
Chodziło o jednoliterowe nazwy.

2020-11-16 22:18 UTC, merged

2020-11-21 09:01 UTC, nowszy94 commented on src/main/java/pl/sda/library/domain/service/BookService.java
> +        int i = 0;
nieuzywana zmienna

2020-11-21 09:01 UTC, nowszy94 commented on src/main/java/pl/sda/library/domain/model/Book.java
> +    public boolean equals(Object o) {
mysle ze tutaj mozemy zrobic wyjatek, ze wzgledu na to ze jest to wygenerowane przez intellij

Lepsza opcja byłoby użycie adnotacji z lomboka @EqualsAndHashCode

2020-11-21 09:01 UTC, nowszy94 commented on src/main/java/pl/sda/library/domain/service/BookService.java
> +        if(allByTitle.size() > 0) {
formatowanie

2020-11-21 09:01 UTC, nowszy94 commented on src/main/java/pl/sda/library/domain/service/BookService.java
> +                    break;
zamiast break mozna zrobic return true

2020-11-21 09:19 UTC, tkrutowski commented on src/main/java/pl/sda/library/domain/model/Book.java
> +    public boolean equals(Object o) {
Lombok porównuje wszystkie pola a ja nie chce wszystkich tylko wybrane

2020-11-21 09:20 UTC, tkrutowski commented on src/main/java/pl/sda/library/domain/service/BookService.java
> +                    break;
racja